// <auto-generated />
using System;
using CommunityComplaints.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityComplaints.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424215123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommunityComplaints.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AnnouncementId")
                        .HasName("PK__Announce__9DE44574EE8650C9");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("CommunityComplaints.Models.AnnouncementRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Announce__3214EC07E46DC71D");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AnnouncementId", "UserId" }, "UQ_Announcement_User")
                        .IsUnique();

                    b.ToTable("AnnouncementReads");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Assignme__32499E7762CCCBD0");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("StaffId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__Comments__C3B4DFCA9EF283F8");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Medium");

                    b.HasKey("ComplaintId")
                        .HasName("PK__Complain__740D898F7BDD9E7F");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED9131919E");

                    b.HasIndex(new[] { "Name" }, "UQ__Departme__737584F62F67EDAE")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Feedback")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("RatingId")
                        .HasName("PK__Ratings__FCCDF87CF369A096");

                    b.HasIndex("ResidentId");

                    b.HasIndex(new[] { "ComplaintId" }, "UQ__Ratings__740D898E9829F971")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("CommunityComplaints.Models.ResolutionStage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StageId")
                        .HasName("PK__Resoluti__03EB7AD8E107CDCE");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("StaffId");

                    b.ToTable("ResolutionStages");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A508701EA");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6491384E6")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CommunityComplaints.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CB34D190B");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105349BBCD672")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Announcement", b =>
                {
                    b.HasOne("CommunityComplaints.Models.User", "CreatedByNavigation")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Announcements_User");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("CommunityComplaints.Models.AnnouncementRead", b =>
                {
                    b.HasOne("CommunityComplaints.Models.Announcement", "Announcement")
                        .WithMany("AnnouncementReads")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reads_Announcement");

                    b.HasOne("CommunityComplaints.Models.User", "User")
                        .WithMany("AnnouncementReads")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reads_User");

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Assignment", b =>
                {
                    b.HasOne("CommunityComplaints.Models.User", "AssignedByNavigation")
                        .WithMany("AssignmentAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_AssignedBy");

                    b.HasOne("CommunityComplaints.Models.Complaint", "Complaint")
                        .WithMany("Assignments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Complaint");

                    b.HasOne("CommunityComplaints.Models.User", "Staff")
                        .WithMany("AssignmentStaffs")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Staff");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Complaint");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Comment", b =>
                {
                    b.HasOne("CommunityComplaints.Models.Complaint", "Complaint")
                        .WithMany("Comments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comments_Complaint");

                    b.HasOne("CommunityComplaints.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_User");

                    b.Navigation("Complaint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Complaint", b =>
                {
                    b.HasOne("CommunityComplaints.Models.Department", "Department")
                        .WithMany("Complaints")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Complaints_Department");

                    b.HasOne("CommunityComplaints.Models.User", "Resident")
                        .WithMany("Complaints")
                        .HasForeignKey("ResidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Complaints_Resident");

                    b.Navigation("Department");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Rating", b =>
                {
                    b.HasOne("CommunityComplaints.Models.Complaint", "Complaint")
                        .WithOne("Rating")
                        .HasForeignKey("CommunityComplaints.Models.Rating", "ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Complaint");

                    b.HasOne("CommunityComplaints.Models.User", "Resident")
                        .WithMany("Ratings")
                        .HasForeignKey("ResidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Resident");

                    b.Navigation("Complaint");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("CommunityComplaints.Models.ResolutionStage", b =>
                {
                    b.HasOne("CommunityComplaints.Models.Complaint", "Complaint")
                        .WithMany("ResolutionStages")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Stages_Complaint");

                    b.HasOne("CommunityComplaints.Models.User", "Staff")
                        .WithMany("ResolutionStages")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_Stages_Staff");

                    b.Navigation("Complaint");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CommunityComplaints.Models.User", b =>
                {
                    b.HasOne("CommunityComplaints.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Announcement", b =>
                {
                    b.Navigation("AnnouncementReads");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Complaint", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");

                    b.Navigation("Rating");

                    b.Navigation("ResolutionStages");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Department", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("CommunityComplaints.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CommunityComplaints.Models.User", b =>
                {
                    b.Navigation("AnnouncementReads");

                    b.Navigation("Announcements");

                    b.Navigation("AssignmentAssignedByNavigations");

                    b.Navigation("AssignmentStaffs");

                    b.Navigation("Comments");

                    b.Navigation("Complaints");

                    b.Navigation("Ratings");

                    b.Navigation("ResolutionStages");
                });
#pragma warning restore 612, 618
        }
    }
}
